name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main  # Déclencher uniquement sur les pushs vers la branche main

jobs:
  deploy:
    name: 🎉 Deploy to FTP
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout code
      uses: actions/checkout@v3

    - name: 🔑 Setup FTP deployment
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_HOST }}             # Hôte FTP (défini comme secret)
        user: ${{ secrets.FTP_USER }}             # Utilisateur FTP (défini comme secret)
        password: ${{ secrets.FTP_PASSWORD }}     # Mot de passe FTP (défini comme secret)
        forceSsl: true                            # Forcer SSL (FTPS) pour sécuriser la connexion
        localDir: ./                              # Répertoire local (racine du projet)
        remoteDir: /www/                          # Répertoire distant sur le serveur AlwaysData
